######################################################################
# Automatically generated by qmake (2.01a) ?? ????? 17 18:24:58 2013
######################################################################

TEMPLATE = app
#TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mymainwindow.hh plotfield.hh
SOURCES += mymainwindow.cpp main.cpp plotfield.cpp splines.cpp newton.cpp
